export const BRANDS = [
  { name: 'Kia',           count: 23523, models: ['Canival','K5','K7','K8','K9','Niro','RAY','Mohave','Sportage','Stinger','Sorento','morning','Stonic','K3','Tasman','Soul','EV6','EV3','EV9','EV4','pride'] },
  { name: 'Hyundai',       count: 20145, models: ['Avante','Sonata','Grandeur','Tucson','Santa Fe','Palisade','Ioniq 5','Ioniq 6','Staria','Porter'] },
  { name: 'Mercedes-Benz', count: 9238,  models: ['E-Class','S-Class','C-Class','GLE-Class','GLC-Class','A-Class','CLA-Class','CLS-Class','AMG GT','GLB-Class','G-Class','GLA-Class','EQE','EQS','EQB','EQA','EQC','Sprinter','V-Class','SL-Class','B-Class','SLC-Class','CLE-Class'] },
  { name: 'BMW',           count: 8690,  models: ['5 Series','3 Series','7 Series','X5','X3','X6','X7','1 Series','2 Series','4 Series','6 Series','8 Series','M3','M5','iX','i4','i7'] },
  { name: 'Genesis',       count: 6707,  models: ['G80','G90','GV80','GV70','G70','GV60'] },
  { name: 'Chevrolet',     count: 3305,  models: ['Malibu','Trailblazer','Equinox','Traverse','Camaro','Corvette'] },
  { name: 'Renault',       count: 2973,  models: ['SM6','QM6','XM3','Arkana'] },
  { name: 'Audi',          count: 2602,  models: ['A4','A6','A8','Q5','Q7','Q8','A3','A5','A7','e-tron'] },
  { name: 'Porsche',       count: 1517,  models: ['Cayenne','Macan','Panamera','911','Taycan','Boxster'] },
  { name: 'Mini',          count: 1362,  models: ['Cooper','Countryman','Clubman','Convertible','Paceman'] },
  { name: 'Land Rover',    count: 1204,  models: ['Range Rover','Discovery','Defender','Freelander','Evoque','Velar'] },
  { name: 'Volvo',         count: 1106,  models: ['XC90','XC60','XC40','S90','S60','V90','V60','C40'] },
  { name: 'Jeep',          count: 1060,  models: ['Wrangler','Grand Cherokee','Cherokee','Compass','Renegade','Gladiator'] },
  { name: 'Volkswagen',    count: 1019,  models: ['Golf','Tiguan','Passat','Polo','Arteon','Touareg','ID.4','ID.6'] },
  { name: 'Ford',          count: 905,   models: ['Explorer','F-150','Mustang','Bronco','Edge','Escape','Expedition'] },
  { name: 'Tesla',         count: 693,   models: ['Model 3','Model Y','Model S','Model X','Cybertruck'] },
  { name: 'Lexus',         count: 551,   models: ['ES','RX','NX','LX','GX','IS','LS','UX','LC','RC'] },
  { name: 'Toyota',        count: 433,   models: ['Camry','RAV4','Land Cruiser','Prius','Highlander','Corolla','Alphard','Vellfire'] },
  { name: 'Lincoln',       count: 353,   models: ['Navigator','Aviator','Corsair','Nautilus','Continental'] },
  { name: 'Maserati',      count: 293,   models: ['Ghibli','Quattroporte','Levante','GranTurismo','MC20'] },
  { name: 'Honda',         count: 279,   models: ['Accord','CR-V','Pilot','Odyssey','Civic','HR-V','Passport'] },
  { name: 'Cadillac',      count: 265,   models: ['Escalade','CT5','CT4','XT5','XT6','Lyriq'] },
  { name: 'Peugeot',       count: 239,   models: ['508','3008','5008','208','2008','408'] },
  { name: 'Jaguar',        count: 194,   models: ['F-Pace','E-Pace','XE','XF','XJ','F-Type','I-Pace'] },
  { name: 'Bentley',       count: 161,   models: ['Bentayga','Continental GT','Flying Spur','Mulsanne'] },
  { name: 'Infiniti',      count: 99,    models: ['QX80','QX60','QX50','Q50','Q60','QX55'] },
  { name: 'Nissan',        count: 89,    models: ['Patrol','Murano','Pathfinder','Altima','370Z','GT-R','Leaf','Ariya'] },
  { name: 'Lamborghini',   count: 85,    models: ['Urus','Huracan','Aventador','Revuelto'] },
  { name: 'Rolls-Royce',   count: 82,    models: ['Ghost','Phantom','Cullinan','Wraith','Dawn','Spectre'] },
  { name: 'Ferrari',       count: 64,    models: ['Roma','Portofino','SF90','F8','812','296','Purosangue'] },
  { name: 'Dodge',         count: 38,    models: ['Challenger','Charger','Durango','Ram'] },
  { name: 'GMC',           count: 34,    models: ['Yukon','Sierra','Acadia','Terrain','Canyon','Hummer EV'] },
  { name: 'Mclaren',       count: 26,    models: ['720S','765LT','Artura','GT','Speedtail'] },
  { name: 'Astonmartin',   count: 23,    models: ['DB11','Vantage','DBX','DBS','Valkyrie'] },
  { name: 'Suzuki',        count: 17,    models: ['Jimny','Swift','Vitara','Ertiga'] },
  { name: 'BYD',           count: 7,     models: ['Han','Tang','Seal','Dolphin','Atto 3'] },
  { name: 'Mazda',         count: 6,     models: ['CX-5','CX-9','CX-60','Mazda3','MX-5'] },
  { name: 'Fiat',          count: 5,     models: ['500','Tipo','500X','Panda'] },
];

export const FUEL_TYPES    = ['Бүгд', 'Бензин', 'Дизель', 'Цахилгаан', 'Гибрид'];
export const TRANSMISSIONS = ['Бүгд', 'Автомат', 'Механик'];
export const SORT_OPTIONS  = [
  { value: 'priceAsc',    label: 'Үнэ ↑' },
  { value: 'priceDesc',   label: 'Үнэ ↓' },
  { value: 'mileageAsc',  label: 'Гүйлт ↑' },
  { value: 'mileageDesc', label: 'Гүйлт ↓' },
  { value: 'yearDesc',    label: 'Он ↓' },
  { value: 'new',         label: 'Шинэ' },
];